[theme]
base = "light"
primaryColor = "#0B2E59"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#333333"
font = "sans serif"

[client]
toolbarMode = "off"
showErrorDetails = false
